[package]
name = "dylan/voltz"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@0.4.1"
Signal = "sleitnick/signal@1.2.0"
Binder = "4812571/binder@0.1.1"